spring: 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASS}

springdoc:
  api-docs:
    enabled: true 
    path: /file/v3/api-docs
  swagger-ui:
    enabled: true
    path: /file/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/file"

files:
  storage-dir: ${STORAGE_DIR}