spring:
  cloud:
    gateway:
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/api/organizations, /api/organizations/**, /auth/organization/**, /organization/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users, /api/users/**, /auth/user/**, /user/**

        - id: vacancy-service
          uri: lb://vacancy-service
          predicates:
            - Path=/api/vacancies, /api/vacancies/**, /vacancy/**
            
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file, /file/**

        - id: notification-ws
          uri: lb:ws://notification-service
          predicates:
            - Path=/ws/**
            
        - id: kafka-ui
          uri: http://kafka-ui:8080 # in docker
          predicates:
            - Path=/kafka/** 
          # filters:
          #   - StripPrefix=1


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Gateway Service
        url: /v3/api-docs

      - name: Vacancy Service
        url: /vacancy/v3/api-docs

      - name: User Service
        url: /user/v3/api-docs

      - name: Organization Service
        url: /organization/v3/api-docs

      - name: File Service
        url: /file/v3/api-docs

