springdoc:
  api-docs:
    enabled: true 
    path: /organization/v3/api-docs
  swagger-ui:
    enabled: true
    path: /organization/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/organization"

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000  # 1 hour

spring:
  r2dbc:
    # url: r2dbc:postgresql://localhost:5432/organization_db
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  flyway:
    url: ${DB_URL_2}
    locations: classpath:db/migration
    baseline-on-migrate: true

