springdoc:
  api-docs:
    enabled: true 
    path: /user/v3/api-docs
  swagger-ui:
    enabled: true
    path: /user/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/user"

resilience4j:
  circuitbreaker:
    instances:
      vacancy-service:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s
        registerHealthIndicator: true
        ignore-exceptions:
        - feign.FeignException$NotFound

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASS}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000  # 1 hour

supervisor:
  email: ${SUPERVISOR_EMAIL}
  pass: ${SUPERVISOR_PASS}