springdoc:
  api-docs:
    enabled: true 
    path: /vacancy/v3/api-docs
  swagger-ui:
    enabled: true
    path: /vacancy/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/vacancy"

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s
        registerHealthIndicator: true
        ignore-exceptions:
        - feign.FeignException$NotFound
        
      organization-service:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s
        registerHealthIndicator: true
        ignore-exceptions:
        - feign.FeignException$NotFound

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASS}

# eureka:
#   client:
#     service-url:
#       # todo: change in docker
#       # defaultZone: http://eureka-server:8761/eureka/
#       defaultZone: http://localhost:8761/eureka/
